### ISSUE TITLE
About submodules

### ISSUE THREAD

**Issue by Aloure** [DerekCresswell/RigidBodySimulator#3]
Right now GLFW and GL3W are coming from my forked repositories. Control of these repositories are mine but this is your project. So please fork both repositories from [here](https://github.com/Aloure/glfw) and [here](https://github.com/Aloure/gl3w). Then delete both of them and add yours.

Here is how to delete:
[https://gist.github.com/myusuf3/7f645819ded92bda6677](https://gist.github.com/myusuf3/7f645819ded92bda6677)

And you can add like this:
``` sh
git submodule add {repository link here}
```

**Comment by DerekCresswell** [comment]
Fixed
